# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "bastille-day"
license = "MIT"
licenselink = "https://github.com/yrezgui/hugo-bastille-day/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/yrezgui/hugo-bastille-day"
tags = ["simple", "documentation"]
features = ["documentation"]
min_version = 0.18

[author]
  name = "Yacine Rezgui"
  homepage = "http://www.yrezgui.com"
